---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-1-deployment
  labels:
    app: microservice-1
spec:
  selector:
    matchLabels:
      app: microservice-1
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-1
    spec:
      containers:
      - name: microservice-1
        image: aunghtayoo/microservice-1:1.0.0
        ports:
        - containerPort: 8082
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
        volumeMounts:
        - name: microservice-1-config-volume
          readOnly: true
          mountPath: /opt/mutu/external_application.yaml
          subPath: external_application.yaml
      volumes:
        - name: microservice-1-config-volume
          configMap:
            name: microservice-1-config
            items:
            - key: external_application.yaml
              path: external_application.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-1-service
  labels:
    app: microservice-1-service
spec:
  selector:
    app: microservice-1
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-1-config
  labels:
      app: microservice-1-config
data:
  external_application.yaml: |
    server:
      port: 8082
      servlet:
        contextPath: /ms1
    ms2_url: http://192.168.50.222:9992/ms2
---
