---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ms1
            pathType: Prefix
            backend:
              service:
                name: microservice-1-service
                port:
                  number: 8082
          - path: /ms2
            pathType: Prefix
            backend:
              service:
                name: microservice-2-service
                port:
                  number: 8082
---
